# NumPy

NumPy - Numerical Python
Biblioteca para cálculos matemáticos
Fornece a base matemática necessária para análise de dados,
Aprendizado de Máquina, Estatica, entre outros.
Facilita:
- A criação de Array Matrizes
- A leitura de database
- Álgebra linear

In [22]:
import numpy as np

Também é possivel importar desta forma:
    
from numpy import *

Lista de dados Python
- Conjunto de valores de qualquer tipo:
E.: lista = [1,20,'Texto', True, 2.3]

Array NumPy:
- Conjunto de valores de apenas um tipo;
- São mais eficientes do que lista no que diz respeito o uso de memória do computaor;

In [23]:
 array_1 = np.array([1,2,3,4,5])

In [24]:
print(type(array_1))

<class 'numpy.ndarray'>


In [25]:
print(array_1)

[1 2 3 4 5]


In [26]:
print(array_1[1])

2


In [27]:
# Mostranto o tamanho da linha(quantos elemntos tem na linha)
print(array_1.size)

5


# Propiedades/Atributos do NumPy

In [28]:
# Shape retorna a dimensão/formato do array
print(array_1.shape)

(5,)


In [29]:
# Retorna o tipo dos dados amazenados
print(array_1.dtype)

int32


In [30]:
# Mostra tamanho que cada elemento ocupa na memória 
print(array_1.itemsize)

4


In [31]:
# Retorna o quanto ele ocupa de memória no total (4 vezes 5 = 20 (20 espaços de memória dos elemanto))
print(array_1.nbytes)

20


# Tipos de Arrays

In [32]:
# Array de inteitos 
array_inteiros = np.array([1,2,3,4,5])
print(array_inteiros)

[1 2 3 4 5]


In [33]:
# Arre=ay de Números Reais
array_reais = np.array([2.5,1.0,5.2,10.2])
print(array_reais)

[ 2.5  1.   5.2 10.2]


In [34]:
# Array de Strings
array_strings = np.array(['Python', 'JavaScript', 'Java'])
print(array_strings)

['Python' 'JavaScript' 'Java']


In [35]:
# Array de valores Booleanos
array_booleanos = np.array([True, True, False])
print(array_booleanos)

[ True  True False]


In [36]:
array_reais_forcado = np.array([5, 2 , 1, 67, 1], dtype=np.float32)
print(array_reais_forcado.dtype)
print(array_reais_forcado)

float32
[ 5.  2.  1. 67.  1.]


# Matiz

In [37]:
matriz_1 = np.array([[1, 2], [3, 4], [4, 5], [5, 6]])
print(matriz_1)

[[1 2]
 [3 4]
 [4 5]
 [5 6]]


In [38]:
# A dimeção dessa coluna é 4(linhas) por 2 (colunas)

print(matriz_1.shape)

(4, 2)


In [39]:
# Para imprimir basta informar a linha e coluna entre colchetes

print(matriz_1[2][1])
# Imprimir de outra forma
print(matriz_1[2,0])

5
4


In [40]:
# Para substituir também utiliza colchetes
matriz_1[2][1] = 10
print(matriz_1[2][1])

# Outra forma
matriz_1[2][0] = 15
print(matriz_1[2,0])

# Matriz completa com os dados substituidos
print(matriz_1)

10
15
[[ 1  2]
 [ 3  4]
 [15 10]
 [ 5  6]]


# Funções para Array

In [41]:
# Cumsum - retorna uma matriz com a soma acumulada dos valores

array_2 = np.array([2, 3, 1, 5, 10])
print(array_2.cumsum())

[ 2  5  6 11 21]


In [42]:
# Cria uma matriz seguindo a logica do range nativo do python

array_3 = np.arange(5)
print(array_3)

array_4 = np.arange(2, 10, 2)
print(array_4)

[0 1 2 3 4]
[2 4 6 8]


In [43]:
# Linspace
# Cria um array com elementos espacados igualmente
# Entre um valor inicial e facil
# Linspace(inicio, fim, quantidade de elememtos entre eles)

array_5 = np.linspace(1, 10, 4)
print(array_5)

[ 1.  4.  7. 10.]


In [44]:
#Zeros cria um array somente com elementos zeros 

array_6 = np.zeros(15)
print(array_6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [45]:
# array_equal
# compara se 2 arrays são iguais (true ou false)
array_7 = np.array([1,2,3,4])
array_8 = np.array([5,6,7,8])
print(np.array_equal(array_7, array_8))

False


In [46]:
array_9 = np.array([1,2,3,4])
array_10 = np.array([1,2,3,4])
print(np.array_equal(array_9, array_10))

True


In [47]:
# min
# Retorna o menor valor

print(array_10.min())

1


In [48]:
# max
# Retorna o maior valor (máximo)

print(array_10.max())

4


In [49]:
# repeat
# Cria um novo array com os elemento repetidos
# Repete por número

print(array_10)
print(np.repeat(array_10, 3))

[1 2 3 4]
[1 1 1 2 2 2 3 3 3 4 4 4]


In [50]:
# tile
# Repete os elemento de uma array
# Repete os elemnetos na ordem original do array

print(array_10)
print(np.tile(array_10, 3))

[1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


In [51]:
# concatenate
# Junta 2 array e gera um com todos os elementos

print(np.concatenate((array_7, array_8), axis=0))

[1 2 3 4 5 6 7 8]


# Funções para Matriz

In [52]:
# eye - cria matriz quadrada, todos os elementos são zero com execeção
# dos elementos que foram a diagonal principal, estes recebem o valor 1

matriz_2 = np.eye(3)
print(matriz_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
# DIAG
# Define os elementos que ficarão na giagonal principal da matriz

matriz_3 = np.diag(np.array([2,4,1,0]))
print(matriz_3)

[[2 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 0]]


In [54]:
# Ones
# Cria uma matriz com todos os valores sendo 1

matriz_4 = np.ones((3,4))
print(matriz_4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [55]:
# Matriz
# Coverte listas bidimencional em matriz numpy

lista_bidimensional = [[1,2,3],[4,5,6],[7,8,9]]
matriz_5 = np.matrix(lista_bidimensional)
print(matriz_5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
# flatten
# transforma a matris principal em uma nova em que todos os elementos ficarão na primeira linha

array_11 = matriz_5.flatten()
print(array_11)

[[1 2 3 4 5 6 7 8 9]]


# Propriedade para Matriz

In [57]:
# shape
# imprime quantas linhas e colunas a matriz possui

print(matriz_5.shape)

(3, 3)


In [58]:
# ndim
# Retorna a dimensão da matriz

print(matriz_5.ndim)

2


In [59]:
# size
# Retrona quantos elementos possui a matriz
print(matriz_5.size)

9


# Slicing em Arrays

In [60]:
array_12 = np.array([10, 4, 2, 1, 11, 44])
print(array_12)

[10  4  2  1 11 44]


In [61]:
# Imprime o terceiro elemento do array
print(array_12[2])

2


In [62]:
# Utilizando slicing é possível retornar uma parte do array
# No exemplo a seguir, retorna os elementos da posição 1 até a 3
print(array_12[1:3])

[4 2]


In [63]:
# No exemplo a seguir, retornará os elementos nas posições 1, 3 e 5
print(array_12[::2])

[10  2 11]


In [64]:
# No exemplo a seguir, retornará os elementos das posições 0 e 3 (salto será 3)
print(array_12[0:4:3])

[10  1]


# Trabalhando com Dataset

In [65]:
arquivo = np.loadtxt('country_wise_latest.csv', delimiter=',', usecols=(1,2,3), skiprows=1, dtype=np.int32)


In [66]:
print(arquivo)

[[  36263    1269   25198]
 [   4880     144    2745]
 [  27973    1163   18837]
 [    907      52     803]
 [    950      41     242]
 [     86       3      65]
 [ 167416    3059   72575]
 [  37390     711   26665]
 [  15303     167    9311]
 [  20558     713   18246]
 [  30446     423   23242]
 [    382      11      91]
 [  39482     141   36110]
 [ 226225    2965  125683]
 [    110       7      94]
 [  67251     538   60492]
 [  66428    9822   17452]
 [     48       2      26]
 [   1770      35    1036]
 [     99       0      86]
 [  71181    2647   21478]
 [  10498     294    4930]
 [    739       2      63]
 [2442375   87618 1846641]
 [    141       3     138]
 [  10621     347    5585]
 [   1100      53     926]
 [    350       6     292]
 [    378       1     301]
 [   2328      22    1550]
 [    226       0     147]
 [  17110     391   14539]
 [ 116458    8944       0]
 [   4599      59    1546]
 [    922      75     810]
 [ 347923    9187  319954]
 [  86783    4656   78869]
 

# Conceitos Básicos de Estatística

In [67]:
array_13 = np.array([15, 23, 72, 22])

In [68]:
# sum
# Retorna o resultado da soma de todos os elementos
print(np.sum(array_13))

132


In [69]:
# prod
# Retorna o resultado do produto(multiplicação) de todos os elementos
print(np.prod(array_13))

546480


In [70]:
# cumsum
# Retorna uma array com o resultado da soma acumulada de todos os elementos
print(np.cumsum(array_13))

[ 15  38 110 132]


In [71]:
# mean
# Retorna a média entre os elementos do array
print(np.mean(array_13))

33.0


In [74]:
# Mediana
# Retorna o valor central do array (entre os array do meio)
print(np.median(array_13))

22.5


In [75]:
# Desvio Padrão
# Variação dos dados em relação à média
# Também chamado de dispersão
print(np.std(array_13))

22.726636354727024


In [72]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
print(np.sum(matriz, axis=0))

[12 15 18]
