# NumPy

NumPy - Numerical Python
Biblioteca para cálculos matemáticos
Fornece a base matemática necessária para análise de dados,
Aprendizado de Máquina, Estatica, entre outros.
Facilita:
- A criação de Array Matrizes
- A leitura de database
- Álgebra linear

In [1]:
import numpy as np

Também é possivel importar desta forma:
    
from numpy import *

Lista de dados Python
- Conjunto de valores de qualquer tipo:
E.: lista = [1,20,'Texto', True, 2.3]

Array NumPy:
- Conjunto de valores de apenas um tipo;
- São mais eficientes do que lista no que diz respeito o uso de memória do computaor;

In [6]:
 array_1 = np.array([1,2,3,4,5])

In [7]:
print(type(array_1))

<class 'numpy.ndarray'>


In [8]:
print(array_1)

[1 2 3 4 5]


In [11]:
print(array_1[1])

2


In [14]:
# Mostranto o tamanho da linha(quantos elemntos tem na linha)
print(array_1.size)

5


# Propiedades/Atributos do NumPy

In [15]:
# Shape retorna a dimensão/formato do array
print(array_1.shape)

(5,)


In [16]:
# Retorna o tipo dos dados amazenados
print(array_1.dtype)

int32


In [17]:
# Mostra tamanho que cada elemento ocupa na memória 
print(array_1.itemsize)

4


In [18]:
# Retorna o quanto ele ocupa de memória no total (4 vezes 5 = 20 (20 espaços de memória dos elemanto))
print(array_1.nbytes)

20


# Tipos de Arrays

In [19]:
# Array de inteitos 
array_inteiros = np.array([1,2,3,4,5])
print(array_inteiros)

[1 2 3 4 5]


In [20]:
# Arre=ay de Números Reais
array_reais = np.array([2.5,1.0,5.2,10.2])
print(array_reais)

[ 2.5  1.   5.2 10.2]


In [21]:
# Array de Strings
array_strings = np.array(['Python', 'JavaScript', 'Java'])
print(array_strings)

['Python' 'JavaScript' 'Java']


In [22]:
# Array de valores Booleanos
array_booleanos = np.array([True, True, False])
print(array_booleanos)

[ True  True False]


In [28]:
array_reais_forcado = np.array([5, 2 , 1, 67, 1], dtype=np.float32)
print(array_reais_forcado.dtype)
print(array_reais_forcado)

float32
[ 5.  2.  1. 67.  1.]
