# NumPy

NumPy - Numerical Python
Biblioteca para cálculos matemáticos
Fornece a base matemática necessária para análise de dados,
Aprendizado de Máquina, Estatica, entre outros.
Facilita:
- A criação de Array Matrizes
- A leitura de database
- Álgebra linear

In [1]:
import numpy as np

Também é possivel importar desta forma:
    
from numpy import *

Lista de dados Python
- Conjunto de valores de qualquer tipo:
E.: lista = [1,20,'Texto', True, 2.3]

Array NumPy:
- Conjunto de valores de apenas um tipo;
- São mais eficientes do que lista no que diz respeito o uso de memória do computaor;

In [6]:
 array_1 = np.array([1,2,3,4,5])

In [7]:
print(type(array_1))

<class 'numpy.ndarray'>


In [8]:
print(array_1)

[1 2 3 4 5]


In [11]:
print(array_1[1])

2


In [14]:
# Mostranto o tamanho da linha(quantos elemntos tem na linha)
print(array_1.size)

5


# Propiedades/Atributos do NumPy

In [15]:
# Shape retorna a dimensão/formato do array
print(array_1.shape)

(5,)


In [16]:
# Retorna o tipo dos dados amazenados
print(array_1.dtype)

int32


In [17]:
# Mostra tamanho que cada elemento ocupa na memória 
print(array_1.itemsize)

4


In [18]:
# Retorna o quanto ele ocupa de memória no total (4 vezes 5 = 20 (20 espaços de memória dos elemanto))
print(array_1.nbytes)

20


# Tipos de Arrays

In [19]:
# Array de inteitos 
array_inteiros = np.array([1,2,3,4,5])
print(array_inteiros)

[1 2 3 4 5]


In [20]:
# Arre=ay de Números Reais
array_reais = np.array([2.5,1.0,5.2,10.2])
print(array_reais)

[ 2.5  1.   5.2 10.2]


In [21]:
# Array de Strings
array_strings = np.array(['Python', 'JavaScript', 'Java'])
print(array_strings)

['Python' 'JavaScript' 'Java']


In [22]:
# Array de valores Booleanos
array_booleanos = np.array([True, True, False])
print(array_booleanos)

[ True  True False]


In [28]:
array_reais_forcado = np.array([5, 2 , 1, 67, 1], dtype=np.float32)
print(array_reais_forcado.dtype)
print(array_reais_forcado)

float32
[ 5.  2.  1. 67.  1.]


# Matiz

In [5]:
matriz_1 = np.array([[1, 2], [3, 4], [4, 5], [5, 6]])
print(matriz_1)

[[1 2]
 [3 4]
 [4 5]
 [5 6]]


In [6]:
# A dimeção dessa coluna é 4(linhas) por 2 (colunas)

print(matriz_1.shape)

(4, 2)


In [7]:
# Para imprimir basta informar a linha e coluna entre colchetes

print(matriz_1[2][1])
# Imprimir de outra forma
print(matriz_1[2,0])

5
4


In [9]:
# Para substituir também utiliza colchetes
matriz_1[2][1] = 10
print(matriz_1[2][1])

# Outra forma
matriz_1[2][0] = 15
print(matriz_1[2,0])

# Matriz completa com os dados substituidos
print(matriz_1)

10
15
[[ 1  2]
 [ 3  4]
 [15 10]
 [ 5  6]]


# Funções para Array

In [11]:
# Cumsum - retorna uma matriz com a soma acumulada dos valores

array_2 = np.array([2, 3, 1, 5, 10])
print(array_2.cumsum())

[ 2  5  6 11 21]


In [16]:
# Cria uma matriz seguindo a logica do range nativo do python

array_3 = np.arange(5)
print(array_3)

array_4 = np.arange(2, 10, 2)
print(array_4)

[0 1 2 3 4]
[2 4 6 8]


In [20]:
# Linspace
# Cria um array com elementos espacados igualmente
# Entre um valor inicial e facil
# Linspace(inicio, fim, quantidade de elememtos entre eles)

array_5 = np.linspace(1, 10, 4)
print(array_5)

[ 1.  4.  7. 10.]


In [21]:
#Zeros cria um array somente com elementos zeros 

array_6 = np.zeros(15)
print(array_6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Funções para Matriz

In [23]:
# eye - cria matriz quadrada, todos os elementos são zero com execeção
# dos elementos que foram a diagonal principal, estes recebem o valor 1

matriz_2 = np.eye(3)
print(matriz_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
